name: google-bert/bert-base-multilingual-cased

tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${..name}

encoder:
    _target_: transformers.AutoModelForMaskedLM.from_pretrained
    pretrained_model_name_or_path: ${..name}
