# Training configuration for forgetting data from encoder
objective: "forgetting"

seed: 42 # Meaning of life, the universe, and everything
ckpt_path: ./outputs/${.objective}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/

# Noise configuration for forgetting
noise:
  noise_std: 0.01
  noise_type: "gaussian"  # or "uniform"
