defaults:
  - paths
  - model: multilingual_bert_with_head
  - tracker: wandb
  - training: head-training
  - data: historical_text
  - _self_

hydra:
  run:
    dir: ./outputs/${training.objective}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  job_logging:
    root:
      level: INFO # Could be DEBUG, INFO, WARNING, ERROR, CRITICAL
