defaults:
  - paths
  - model: multilingual_bert_for_mlm
  - tracker: wandb
  - training: anti-training
  - data: historical_text_sample
  - _self_

hydra:
  run:
    dir: ./outputs/${training.objective}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  job_logging:
    root:
      level: INFO # Could be DEBUG, INFO, WARNING, ERROR, CRITICAL
